// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/kotlin-descriptor.proto

package google.protobuf;

public final class KotlinDescriptor {
  private KotlinDescriptor() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(google.protobuf.KotlinDescriptor.kotlinMessageOptions);
    registry.add(google.protobuf.KotlinDescriptor.kotlinFieldOptions);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface KotlinMessageOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:google.protobuf.KotlinMessageOptions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool generate_realm_object = 2 [default = false];</code>
     */
    boolean hasGenerateRealmObject();
    /**
     * <code>optional bool generate_realm_object = 2 [default = false];</code>
     */
    boolean getGenerateRealmObject();
  }
  /**
   * Protobuf type {@code google.protobuf.KotlinMessageOptions}
   */
  public  static final class KotlinMessageOptions extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:google.protobuf.KotlinMessageOptions)
      KotlinMessageOptionsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KotlinMessageOptions.newBuilder() to construct.
    private KotlinMessageOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KotlinMessageOptions() {
      generateRealmObject_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private KotlinMessageOptions(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              generateRealmObject_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return google.protobuf.KotlinDescriptor.internal_static_google_protobuf_KotlinMessageOptions_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return google.protobuf.KotlinDescriptor.internal_static_google_protobuf_KotlinMessageOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              google.protobuf.KotlinDescriptor.KotlinMessageOptions.class, google.protobuf.KotlinDescriptor.KotlinMessageOptions.Builder.class);
    }

    private int bitField0_;
    public static final int GENERATE_REALM_OBJECT_FIELD_NUMBER = 2;
    private boolean generateRealmObject_;
    /**
     * <code>optional bool generate_realm_object = 2 [default = false];</code>
     */
    public boolean hasGenerateRealmObject() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool generate_realm_object = 2 [default = false];</code>
     */
    public boolean getGenerateRealmObject() {
      return generateRealmObject_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(2, generateRealmObject_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, generateRealmObject_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof google.protobuf.KotlinDescriptor.KotlinMessageOptions)) {
        return super.equals(obj);
      }
      google.protobuf.KotlinDescriptor.KotlinMessageOptions other = (google.protobuf.KotlinDescriptor.KotlinMessageOptions) obj;

      boolean result = true;
      result = result && (hasGenerateRealmObject() == other.hasGenerateRealmObject());
      if (hasGenerateRealmObject()) {
        result = result && (getGenerateRealmObject()
            == other.getGenerateRealmObject());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasGenerateRealmObject()) {
        hash = (37 * hash) + GENERATE_REALM_OBJECT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getGenerateRealmObject());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static google.protobuf.KotlinDescriptor.KotlinMessageOptions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.protobuf.KotlinDescriptor.KotlinMessageOptions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.protobuf.KotlinDescriptor.KotlinMessageOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.protobuf.KotlinDescriptor.KotlinMessageOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.protobuf.KotlinDescriptor.KotlinMessageOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.protobuf.KotlinDescriptor.KotlinMessageOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.protobuf.KotlinDescriptor.KotlinMessageOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static google.protobuf.KotlinDescriptor.KotlinMessageOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static google.protobuf.KotlinDescriptor.KotlinMessageOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static google.protobuf.KotlinDescriptor.KotlinMessageOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static google.protobuf.KotlinDescriptor.KotlinMessageOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static google.protobuf.KotlinDescriptor.KotlinMessageOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(google.protobuf.KotlinDescriptor.KotlinMessageOptions prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code google.protobuf.KotlinMessageOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:google.protobuf.KotlinMessageOptions)
        google.protobuf.KotlinDescriptor.KotlinMessageOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return google.protobuf.KotlinDescriptor.internal_static_google_protobuf_KotlinMessageOptions_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return google.protobuf.KotlinDescriptor.internal_static_google_protobuf_KotlinMessageOptions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                google.protobuf.KotlinDescriptor.KotlinMessageOptions.class, google.protobuf.KotlinDescriptor.KotlinMessageOptions.Builder.class);
      }

      // Construct using google.protobuf.KotlinDescriptor.KotlinMessageOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        generateRealmObject_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return google.protobuf.KotlinDescriptor.internal_static_google_protobuf_KotlinMessageOptions_descriptor;
      }

      public google.protobuf.KotlinDescriptor.KotlinMessageOptions getDefaultInstanceForType() {
        return google.protobuf.KotlinDescriptor.KotlinMessageOptions.getDefaultInstance();
      }

      public google.protobuf.KotlinDescriptor.KotlinMessageOptions build() {
        google.protobuf.KotlinDescriptor.KotlinMessageOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public google.protobuf.KotlinDescriptor.KotlinMessageOptions buildPartial() {
        google.protobuf.KotlinDescriptor.KotlinMessageOptions result = new google.protobuf.KotlinDescriptor.KotlinMessageOptions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.generateRealmObject_ = generateRealmObject_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof google.protobuf.KotlinDescriptor.KotlinMessageOptions) {
          return mergeFrom((google.protobuf.KotlinDescriptor.KotlinMessageOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(google.protobuf.KotlinDescriptor.KotlinMessageOptions other) {
        if (other == google.protobuf.KotlinDescriptor.KotlinMessageOptions.getDefaultInstance()) return this;
        if (other.hasGenerateRealmObject()) {
          setGenerateRealmObject(other.getGenerateRealmObject());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        google.protobuf.KotlinDescriptor.KotlinMessageOptions parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (google.protobuf.KotlinDescriptor.KotlinMessageOptions) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean generateRealmObject_ ;
      /**
       * <code>optional bool generate_realm_object = 2 [default = false];</code>
       */
      public boolean hasGenerateRealmObject() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool generate_realm_object = 2 [default = false];</code>
       */
      public boolean getGenerateRealmObject() {
        return generateRealmObject_;
      }
      /**
       * <code>optional bool generate_realm_object = 2 [default = false];</code>
       */
      public Builder setGenerateRealmObject(boolean value) {
        bitField0_ |= 0x00000001;
        generateRealmObject_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool generate_realm_object = 2 [default = false];</code>
       */
      public Builder clearGenerateRealmObject() {
        bitField0_ = (bitField0_ & ~0x00000001);
        generateRealmObject_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:google.protobuf.KotlinMessageOptions)
    }

    // @@protoc_insertion_point(class_scope:google.protobuf.KotlinMessageOptions)
    private static final google.protobuf.KotlinDescriptor.KotlinMessageOptions DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new google.protobuf.KotlinDescriptor.KotlinMessageOptions();
    }

    public static google.protobuf.KotlinDescriptor.KotlinMessageOptions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<KotlinMessageOptions>
        PARSER = new com.google.protobuf.AbstractParser<KotlinMessageOptions>() {
      public KotlinMessageOptions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new KotlinMessageOptions(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<KotlinMessageOptions> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KotlinMessageOptions> getParserForType() {
      return PARSER;
    }

    public google.protobuf.KotlinDescriptor.KotlinMessageOptions getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface KotlinFieldOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:google.protobuf.KotlinFieldOptions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool generate_realm_primary_key = 2 [default = false];</code>
     */
    boolean hasGenerateRealmPrimaryKey();
    /**
     * <code>optional bool generate_realm_primary_key = 2 [default = false];</code>
     */
    boolean getGenerateRealmPrimaryKey();
  }
  /**
   * Protobuf type {@code google.protobuf.KotlinFieldOptions}
   */
  public  static final class KotlinFieldOptions extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:google.protobuf.KotlinFieldOptions)
      KotlinFieldOptionsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KotlinFieldOptions.newBuilder() to construct.
    private KotlinFieldOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KotlinFieldOptions() {
      generateRealmPrimaryKey_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private KotlinFieldOptions(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              generateRealmPrimaryKey_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return google.protobuf.KotlinDescriptor.internal_static_google_protobuf_KotlinFieldOptions_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return google.protobuf.KotlinDescriptor.internal_static_google_protobuf_KotlinFieldOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              google.protobuf.KotlinDescriptor.KotlinFieldOptions.class, google.protobuf.KotlinDescriptor.KotlinFieldOptions.Builder.class);
    }

    private int bitField0_;
    public static final int GENERATE_REALM_PRIMARY_KEY_FIELD_NUMBER = 2;
    private boolean generateRealmPrimaryKey_;
    /**
     * <code>optional bool generate_realm_primary_key = 2 [default = false];</code>
     */
    public boolean hasGenerateRealmPrimaryKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool generate_realm_primary_key = 2 [default = false];</code>
     */
    public boolean getGenerateRealmPrimaryKey() {
      return generateRealmPrimaryKey_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(2, generateRealmPrimaryKey_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, generateRealmPrimaryKey_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof google.protobuf.KotlinDescriptor.KotlinFieldOptions)) {
        return super.equals(obj);
      }
      google.protobuf.KotlinDescriptor.KotlinFieldOptions other = (google.protobuf.KotlinDescriptor.KotlinFieldOptions) obj;

      boolean result = true;
      result = result && (hasGenerateRealmPrimaryKey() == other.hasGenerateRealmPrimaryKey());
      if (hasGenerateRealmPrimaryKey()) {
        result = result && (getGenerateRealmPrimaryKey()
            == other.getGenerateRealmPrimaryKey());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasGenerateRealmPrimaryKey()) {
        hash = (37 * hash) + GENERATE_REALM_PRIMARY_KEY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getGenerateRealmPrimaryKey());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static google.protobuf.KotlinDescriptor.KotlinFieldOptions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.protobuf.KotlinDescriptor.KotlinFieldOptions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.protobuf.KotlinDescriptor.KotlinFieldOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.protobuf.KotlinDescriptor.KotlinFieldOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.protobuf.KotlinDescriptor.KotlinFieldOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static google.protobuf.KotlinDescriptor.KotlinFieldOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static google.protobuf.KotlinDescriptor.KotlinFieldOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static google.protobuf.KotlinDescriptor.KotlinFieldOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static google.protobuf.KotlinDescriptor.KotlinFieldOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static google.protobuf.KotlinDescriptor.KotlinFieldOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static google.protobuf.KotlinDescriptor.KotlinFieldOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static google.protobuf.KotlinDescriptor.KotlinFieldOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(google.protobuf.KotlinDescriptor.KotlinFieldOptions prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code google.protobuf.KotlinFieldOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:google.protobuf.KotlinFieldOptions)
        google.protobuf.KotlinDescriptor.KotlinFieldOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return google.protobuf.KotlinDescriptor.internal_static_google_protobuf_KotlinFieldOptions_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return google.protobuf.KotlinDescriptor.internal_static_google_protobuf_KotlinFieldOptions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                google.protobuf.KotlinDescriptor.KotlinFieldOptions.class, google.protobuf.KotlinDescriptor.KotlinFieldOptions.Builder.class);
      }

      // Construct using google.protobuf.KotlinDescriptor.KotlinFieldOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        generateRealmPrimaryKey_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return google.protobuf.KotlinDescriptor.internal_static_google_protobuf_KotlinFieldOptions_descriptor;
      }

      public google.protobuf.KotlinDescriptor.KotlinFieldOptions getDefaultInstanceForType() {
        return google.protobuf.KotlinDescriptor.KotlinFieldOptions.getDefaultInstance();
      }

      public google.protobuf.KotlinDescriptor.KotlinFieldOptions build() {
        google.protobuf.KotlinDescriptor.KotlinFieldOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public google.protobuf.KotlinDescriptor.KotlinFieldOptions buildPartial() {
        google.protobuf.KotlinDescriptor.KotlinFieldOptions result = new google.protobuf.KotlinDescriptor.KotlinFieldOptions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.generateRealmPrimaryKey_ = generateRealmPrimaryKey_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof google.protobuf.KotlinDescriptor.KotlinFieldOptions) {
          return mergeFrom((google.protobuf.KotlinDescriptor.KotlinFieldOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(google.protobuf.KotlinDescriptor.KotlinFieldOptions other) {
        if (other == google.protobuf.KotlinDescriptor.KotlinFieldOptions.getDefaultInstance()) return this;
        if (other.hasGenerateRealmPrimaryKey()) {
          setGenerateRealmPrimaryKey(other.getGenerateRealmPrimaryKey());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        google.protobuf.KotlinDescriptor.KotlinFieldOptions parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (google.protobuf.KotlinDescriptor.KotlinFieldOptions) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean generateRealmPrimaryKey_ ;
      /**
       * <code>optional bool generate_realm_primary_key = 2 [default = false];</code>
       */
      public boolean hasGenerateRealmPrimaryKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool generate_realm_primary_key = 2 [default = false];</code>
       */
      public boolean getGenerateRealmPrimaryKey() {
        return generateRealmPrimaryKey_;
      }
      /**
       * <code>optional bool generate_realm_primary_key = 2 [default = false];</code>
       */
      public Builder setGenerateRealmPrimaryKey(boolean value) {
        bitField0_ |= 0x00000001;
        generateRealmPrimaryKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool generate_realm_primary_key = 2 [default = false];</code>
       */
      public Builder clearGenerateRealmPrimaryKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        generateRealmPrimaryKey_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:google.protobuf.KotlinFieldOptions)
    }

    // @@protoc_insertion_point(class_scope:google.protobuf.KotlinFieldOptions)
    private static final google.protobuf.KotlinDescriptor.KotlinFieldOptions DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new google.protobuf.KotlinDescriptor.KotlinFieldOptions();
    }

    public static google.protobuf.KotlinDescriptor.KotlinFieldOptions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<KotlinFieldOptions>
        PARSER = new com.google.protobuf.AbstractParser<KotlinFieldOptions>() {
      public KotlinFieldOptions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new KotlinFieldOptions(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<KotlinFieldOptions> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KotlinFieldOptions> getParserForType() {
      return PARSER;
    }

    public google.protobuf.KotlinDescriptor.KotlinFieldOptions getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int KOTLIN_MESSAGE_OPTIONS_FIELD_NUMBER = 50920138;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      google.protobuf.DescriptorProtos.MessageOptions,
      google.protobuf.KotlinDescriptor.KotlinMessageOptions> kotlinMessageOptions = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        google.protobuf.KotlinDescriptor.KotlinMessageOptions.class,
        google.protobuf.KotlinDescriptor.KotlinMessageOptions.getDefaultInstance());
  public static final int KOTLIN_FIELD_OPTIONS_FIELD_NUMBER = 50920139;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      google.protobuf.DescriptorProtos.MessageOptions,
      google.protobuf.KotlinDescriptor.KotlinFieldOptions> kotlinFieldOptions = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        google.protobuf.KotlinDescriptor.KotlinFieldOptions.class,
        google.protobuf.KotlinDescriptor.KotlinFieldOptions.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_KotlinMessageOptions_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_KotlinMessageOptions_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_KotlinFieldOptions_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_KotlinFieldOptions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'google/protobuf/kotlin-descriptor.prot" +
      "o\022\017google.protobuf\032 google/protobuf/desc" +
      "riptor.proto\"<\n\024KotlinMessageOptions\022$\n\025" +
      "generate_realm_object\030\002 \001(\010:\005false\"?\n\022Ko" +
      "tlinFieldOptions\022)\n\032generate_realm_prima" +
      "ry_key\030\002 \001(\010:\005false:i\n\026kotlin_message_op" +
      "tions\022\037.google.protobuf.MessageOptions\030\312" +
      "\365\243\030 \001(\0132%.google.protobuf.KotlinMessageO" +
      "ptions:e\n\024kotlin_field_options\022\037.google." +
      "protobuf.MessageOptions\030\313\365\243\030 \001(\0132#.googl",
      "e.protobuf.KotlinFieldOptions"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
    internal_static_google_protobuf_KotlinMessageOptions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_protobuf_KotlinMessageOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_KotlinMessageOptions_descriptor,
        new java.lang.String[] { "GenerateRealmObject", });
    internal_static_google_protobuf_KotlinFieldOptions_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_protobuf_KotlinFieldOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_KotlinFieldOptions_descriptor,
        new java.lang.String[] { "GenerateRealmPrimaryKey", });
    kotlinMessageOptions.internalInit(descriptor.getExtensions().get(0));
    kotlinFieldOptions.internalInit(descriptor.getExtensions().get(1));
    google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
